import React, { useState, useEffect } from "react";
import api from "../utils/api";
import GlassCard from "./GlassCard";
import {
  Lightbulb,
  Building,
  Briefcase,
  ShieldCheck,
  TrendingUp,
  MapPin,
  Loader2
} from "lucide-react";

const Recommendations = () => {
  const [recs, setRecs] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchRecs = async () => {
      try {
        const res = await api.get("/predictions/recommendations");
        setRecs(res.data);
      } catch (err) {
        console.error("Error fetching recommendations", err);
      } finally {
        setLoading(false);
      }
    };
    fetchRecs();
  }, []);

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center h-[80vh] gap-3">
        <Loader2 className="animate-spin text-cyan-400" size={42} />
        <p className="text-slate-400 text-sm font-semibold">Generating recommendations...</p>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Brand Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h2 className="text-2xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-slate-100 to-slate-400 flex items-center gap-2">
            <Lightbulb className="text-cyan-400" />
            AI RECOMMENDATION CENTER
          </h2>
          <p className="text-xs text-slate-400 uppercase tracking-widest mt-1">
            Real-time advisory policy generated by the economic simulator intelligence
          </p>
        </div>
      </div>

      {/* Grid Layout of Recommendations */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Recommendation 1: Best City */}
        <GlassCard className="relative overflow-hidden flex flex-col justify-between h-[220px]">
          <div>
            <div className="flex items-center gap-2.5 mb-4 text-purple-400 border-b border-white/5 pb-2">
              <MapPin size={18} />
              <h3 className="font-extrabold uppercase tracking-wider text-xs">Optimal Expansion Hub</h3>
            </div>
            <p className="text-[11px] text-slate-400 leading-normal mb-3">
              We analyzed profit factors, operational expenses, and local growth indicators across global economic regions. The hub with highest market health score is:
            </p>
            <div className="text-2xl font-black text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-cyan-400">
              {recs?.best_city}
            </div>
          </div>
          <span className="text-[9px] text-slate-500 font-semibold self-end">
            Telemetry suggests 30% higher survival yield in this city.
          </span>
        </GlassCard>

        {/* Recommendation 2: Best Industry */}
        <GlassCard className="relative overflow-hidden flex flex-col justify-between h-[220px]">
          <div>
            <div className="flex items-center gap-2.5 mb-4 text-cyan-400 border-b border-white/5 pb-2">
              <Building size={18} />
              <h3 className="font-extrabold uppercase tracking-wider text-xs">Target Investment Sector</h3>
            </div>
            <p className="text-[11px] text-slate-400 leading-normal mb-3">
              Sector yields calculated by checking aggregated agent revenues offset by risk levels. The optimal sector for capital allocation is:
            </p>
            <div className="text-2xl font-black text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-emerald-400">
              {recs?.best_industry} Sector
            </div>
          </div>
          <span className="text-[9px] text-slate-500 font-semibold self-end">
            Displays optimal safety margins with high recurring revenue factor.
          </span>
        </GlassCard>

        {/* Recommendation 3: Hiring */}
        <GlassCard className="relative overflow-hidden flex flex-col justify-between h-[220px]">
          <div>
            <div className="flex items-center gap-2.5 mb-4 text-emerald-400 border-b border-white/5 pb-2">
              <Briefcase size={18} />
              <h3 className="font-extrabold uppercase tracking-wider text-xs">Workforce Hiring Directive</h3>
            </div>
            <p className="text-[11px] text-slate-400 leading-normal mb-3">
              Current workforce guidelines derived by analyzing macro GDP growth indexes and unemployment cycles:
            </p>
            <div className="text-slate-200 font-bold text-xs leading-relaxed border-l-2 border-emerald-500 pl-3">
              {recs?.hiring_recommendation}
            </div>
          </div>
          <span className="text-[9px] text-slate-500 font-semibold self-end">
            Updates dynamic employee expenses limits.
          </span>
        </GlassCard>

        {/* Recommendation 4: Risk Strategy */}
        <GlassCard className="relative overflow-hidden flex flex-col justify-between h-[220px]">
          <div>
            <div className="flex items-center gap-2.5 mb-4 text-rose-400 border-b border-white/5 pb-2">
              <ShieldCheck size={18} />
              <h3 className="font-extrabold uppercase tracking-wider text-xs">Stability & Risk Mitigation</h3>
            </div>
            <p className="text-[11px] text-slate-400 leading-normal mb-3">
              System stability directives to avoid economic collapse triggers. Implement the following parameters:
            </p>
            <div className="text-slate-200 font-bold text-xs leading-relaxed border-l-2 border-rose-500 pl-3">
              {recs?.risk_reduction_strategy}
            </div>
          </div>
          <span className="text-[9px] text-slate-500 font-semibold self-end">
            Mitigates bankruptcy risks and halts capital depletion.
          </span>
        </GlassCard>
      </div>

      {/* Advisory warning note */}
      <GlassCard className="border-cyan-500/10 bg-cyan-950/5">
        <div className="flex gap-3">
          <Lightbulb className="text-cyan-400 flex-shrink-0" size={24} />
          <div>
            <h4 className="text-sm font-bold text-slate-200">How recommendation values are calculated:</h4>
            <p className="text-xs text-slate-400 leading-relaxed mt-1.5">
              The advisor system evaluates real-time data from the database. It compares cities by calculating average margins, scores industries based on capital accumulations discounted by agent risk values, and aligns hiring guides to the simulated GDP growth. Ensure simulator is run for at least 12 periods to refine AI outputs.
            </p>
          </div>
        </div>
      </GlassCard>
    </div>
  );
};

export default Recommendations;
