import React, { useState, useEffect } from "react";
import api from "../utils/api";
import GlassCard from "./GlassCard";
import {
  Lightbulb,
  Building,
  Briefcase,
  ShieldCheck,
  TrendingUp,
  MapPin,
  Loader2
} from "lucide-react";

const Recommendations = () => {
  const [recs, setRecs] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchRecs = async () => {
      try {
        const res = await api.get("/predictions/recommendations");
        setRecs(res.data);
      } catch (err) {
        console.error("Error fetching recommendations", err);
      } finally {
        setLoading(false);
      }
    };
    fetchRecs();
  }, []);

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center h-[80vh] gap-3">
        <Loader2 className="animate-spin text-cyan-500" size={42} />
        <p className="text-sm font-semibold" style={{ color: "var(--text-muted)" }}>Generating recommendations...</p>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Brand Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h2 className="text-2xl font-extrabold flex items-center gap-2" style={{ color: "var(--text-primary)" }}>
            <Lightbulb className="text-cyan-500" />
            AI RECOMMENDATION CENTER
          </h2>
          <p className="text-xs uppercase tracking-widest mt-1" style={{ color: "var(--text-muted)" }}>
            Real-time advisory policy generated by the economic simulator intelligence
          </p>
        </div>
      </div>

      {/* Grid Layout of Recommendations */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Recommendation 1: Best City */}
        <GlassCard className="relative overflow-hidden flex flex-col justify-between h-[220px]">
          <div>
            <div className="flex items-center gap-2.5 mb-4 text-purple-500 border-b pb-2" style={{ borderColor: "var(--border-color)" }}>
              <MapPin size={18} />
              <h3 className="font-extrabold uppercase tracking-wider text-xs">Optimal Expansion Hub</h3>
            </div>
            <p className="text-[11px] leading-normal mb-3" style={{ color: "var(--text-secondary)" }}>
              We analyzed profit factors, operational expenses, and local growth indicators across global economic regions. The hub with highest market health score is:
            </p>
            <div className="text-2xl font-black" style={{ color: "var(--text-primary)" }}>
              {recs?.best_city}
            </div>
          </div>
          <span className="text-[9px] font-semibold self-end" style={{ color: "var(--text-muted)" }}>
            Telemetry suggests 30% higher survival yield in this city.
          </span>
        </GlassCard>

        {/* Recommendation 2: Best Industry */}
        <GlassCard className="relative overflow-hidden flex flex-col justify-between h-[220px]">
          <div>
            <div className="flex items-center gap-2.5 mb-4 text-cyan-500 border-b pb-2" style={{ borderColor: "var(--border-color)" }}>
              <Building size={18} />
              <h3 className="font-extrabold uppercase tracking-wider text-xs">Target Investment Sector</h3>
            </div>
            <p className="text-[11px] leading-normal mb-3" style={{ color: "var(--text-secondary)" }}>
              Sector yields calculated by checking aggregated agent revenues offset by risk levels. The optimal sector for capital allocation is:
            </p>
            <div className="text-2xl font-black" style={{ color: "var(--text-primary)" }}>
              {recs?.best_industry} Sector
            </div>
          </div>
          <span className="text-[9px] font-semibold self-end" style={{ color: "var(--text-muted)" }}>
            Displays optimal safety margins with high recurring revenue factor.
          </span>
        </GlassCard>

        {/* Recommendation 3: Hiring */}
        <GlassCard className="relative overflow-hidden flex flex-col justify-between h-[220px]">
          <div>
            <div className="flex items-center gap-2.5 mb-4 text-emerald-500 border-b pb-2" style={{ borderColor: "var(--border-color)" }}>
              <Briefcase size={18} />
              <h3 className="font-extrabold uppercase tracking-wider text-xs">Workforce Hiring Directive</h3>
            </div>
            <p className="text-[11px] leading-normal mb-3" style={{ color: "var(--text-secondary)" }}>
              Current workforce guidelines derived by analyzing macro GDP growth indexes and unemployment cycles:
            </p>
            <div className="font-bold text-xs leading-relaxed border-l-2 border-emerald-500 pl-3" style={{ color: "var(--text-primary)" }}>
              {recs?.hiring_recommendation}
            </div>
          </div>
          <span className="text-[9px] font-semibold self-end" style={{ color: "var(--text-muted)" }}>
            Updates dynamic employee expenses limits.
          </span>
        </GlassCard>

        {/* Recommendation 4: Risk Strategy */}
        <GlassCard className="relative overflow-hidden flex flex-col justify-between h-[220px]">
          <div>
            <div className="flex items-center gap-2.5 mb-4 text-rose-500 border-b pb-2" style={{ borderColor: "var(--border-color)" }}>
              <ShieldCheck size={18} />
              <h3 className="font-extrabold uppercase tracking-wider text-xs">Stability & Risk Mitigation</h3>
            </div>
            <p className="text-[11px] leading-normal mb-3" style={{ color: "var(--text-secondary)" }}>
              System stability directives to avoid economic collapse triggers. Implement the following parameters:
            </p>
            <div className="font-bold text-xs leading-relaxed border-l-2 border-rose-500 pl-3" style={{ color: "var(--text-primary)" }}>
              {recs?.risk_reduction_strategy}
            </div>
          </div>
          <span className="text-[9px] font-semibold self-end" style={{ color: "var(--text-muted)" }}>
            Mitigates bankruptcy risks and halts capital depletion.
          </span>
        </GlassCard>
      </div>

      {/* Advisory warning note */}
      <GlassCard style={{ borderColor: "var(--border-color)", background: "var(--bg-hover)" }}>
        <div className="flex gap-3">
          <Lightbulb className="text-cyan-500 flex-shrink-0" size={24} />
          <div>
            <h4 className="text-sm font-bold" style={{ color: "var(--text-primary)" }}>How recommendation values are calculated:</h4>
            <p className="text-xs leading-relaxed mt-1.5" style={{ color: "var(--text-secondary)" }}>
              The advisor system evaluates real-time data from the database. It compares cities by calculating average margins, scores industries based on capital accumulations discounted by agent risk values, and aligns hiring guides to the simulated GDP growth. Ensure simulator is run for at least 12 periods to refine AI outputs.
            </p>
          </div>
        </div>
      </GlassCard>
    </div>
  );
};

export default Recommendations;
